# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Finetune Mlops pipeline
on: 
    push:
        branches: [main]
jobs:
    quality-check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install uv & lint
          run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                uv add --dev ruff
                uv run ruff check .

    test-coverage:

        runs-on: ubuntu-latest
        needs: quality-check
        strategy:
          fail-fast: true
          matrix: 
            python-version: ["3.13"]
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install uv and python version
            uses: astral-sh/setup-uv@v5
            with: 
                python-version: ${{matrix.python-version}}
                enable-cache: true
          - name: Install dependencies
            run: |
                    uv sync
          - name: test
            run: uv run test.py
          

